spring:
  application:
     name: API-Gateway
  cloud:
   gateway:
    routes:
    - id: api-1
      uri: lb://Welcome-service
      predicates:
         - Path=/welcome
    - id: api-2
      uri: lb://Greating-service
      predicates:
      - Path=/greating
server:
   port: 3333